apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-{{ .Values.services.name }}-service
  name: {{ .Release.Name }}-{{ .Values.services.name }}-service
spec:
  selector:
    name: {{ .Release.Name }}
  {{- .Values.services.spec | toYaml | trim | nindent 2 }}