# !!!WARNING!!!
# Edit config in: ./deploy-config/values.yaml
#
# Default values for service-account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceName: &serviceName ${SERVICE_ACCOUNT_DB_POSTGRESQL_SERVICE_NAME}
servicePort: &servicePort ${SERVICE_ACCOUNT_POSTGRES_DB_PORT}

deployments:
  name: *serviceName
  replicaCount: 1
  containers:
    app:
      name: *serviceName
      image: bitnami/postgresql
      ports:
      - containerPort: *servicePort

services:
  name: *serviceName
  spec:
    type: NodePort
    ports:
    - port: *servicePort
      protocol: TCP
      nodePort: 31001

database:
  storageSize: 10Gi
  accessModes:
    - ReadWriteOnce

secrets:
  stringData:
    POSTGRES_USER: ${SERVICE_ACCOUNT_POSTGRES_USER}
    POSTGRES_PASSWORD: ${SERVICE_ACCOUNT_POSTGRES_PASSWORD}
    POSTGRES_DB: ${SERVICE_ACCOUNT_POSTGRES_DB}