# !!!WARNING!!!
# Edit config in: ./deploy-config/value-secrets.yaml

hydra:
  config:
    dsn: "postgres://${HYDRA_POSTGRES_USER}:${HYDRA_POSTGRES_PASSWORD}@${HELM_HYDRA_DATABASE_CHART_NAME}-${HYDRA_DB_POSTGRESQL_SERVICE_NAME}-service.${KUBE_MICROSERVICES_NAMESPACE}.svc.cluster.local:${HYDRA_POSTGRES_DB_PORT}/${HYDRA_POSTGRES_DB}?sslmode=disable&max_conns=20&max_idle_conns=4"

credentials:
  name: secret-credentials-service-account
  client_id: ${HYDRA_CREDENTIALS_SERVICE_ACCOUNT_CLIENT_ID}
  client_secret: ${HYDRA_CREDENTIALS_SERVICE_ACCOUNT_SECRET}