# # https://github.com/ory/k8s/blob/master/docs/helm/hydra-maester.md
# # src: https://github.com/ory/hydra-maester/tree/master/config/samples
# # src: https://github.com/ory/hydra-maester/blob/master/config/samples/hydra_v1alpha1_oauth2client_user_credentials.yaml

# apiVersion: hydra.ory.sh/v1alpha1
# kind: OAuth2Client
# metadata:
#   name: oauth2-client-service-account
#   {{- if .Release.Namespace }}
#   namespace: {{ .Release.Namespace }}
#   {{- end }}
# spec:
#   grantTypes:
#     # - client_credentials
#     # - implicit
#     - authorization_code
#     - refresh_token
#   responseTypes:
#     - id_token
#     - code
#     - token
#   scope: "read write openid offline"
#   secretName: {{ required "Container secretName is required!" .Values.credentials.name }}
 
#   ## This params don't exits. So finally use make k8s-hydra-reg-client.
#   # redirectUris:
#   #   - http://account.localhost/callback
#   # frontchannelLogoutUri:
#   #   - http://account.localhost/frontchannel-logout
#   # frontchannelLogoutSessionRequired: true
#   # backchannelLogoutUri:
#   #   - http://account.localhost/backchannel-logout
#   # backchannelLogoutSessionRequired: true

#   # # these are optional
#   # postLogoutRedirectUris:
#   #   - 
#   # audience:
#   #   - audience-a
#   #   - audience-b
#   # hydraAdmin:
#   #   # if hydraAdmin is specified, all of these fields are requried,
#   #   # but they can be empty/0
#   #   url: http://hydra-admin.namespace.cluster.domain
#   #   port: 4445
#   #   endpoint: /clients
#   #   forwardedProto: https
#   # tokenEndpointAuthMethod: client_secret_basic