# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ required "Container secretName is required!" .Values.credentials.name }}
#   {{- if .Release.Namespace }}
#   namespace: {{ .Release.Namespace }}
#   {{- end }}
# type: Opaque
# stringData:
#   client_id: {{ required "Container client_id is required!" .Values.credentials.client_id }}
#   client_secret: {{ required "Container client_secret is required!" .Values.credentials.client_secret }}