# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
# 1 control plane node and 2 workers
nodes:
# the control plane node config
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 31000
    hostPort: 5432  # Hydra's PostgreSQL remote connection port.
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 31001
    hostPort: 5432  # Service-account PostgreSQL remote connection port.
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 32000
    hostPort: 2345 # Service-account Golang dlv debug port.
    listenAddress: "0.0.0.0"
    protocol: tcp
# Two workers
# - role: worker
# - role: worker