version: '3.8'
services:
  consent:
    container_name: consent
    hostname: host-consent
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v1.11.7
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - microservices-network
    deploy:
      restart_policy:
        condition: on-failure