apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ required "Container serviceName is required!" .Values.serviceName }}-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.database.storageSize }}
  accessModes: {{ index .Values.database.accessModes }}
  hostPath:
    path: "/mnt/data"