apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Container serviceName is required!" .Values.serviceName }}-secrets
type: Opaque
stringData:
  {{ required "Containers secrets.stringData are required!" .Values.secrets.stringData | toYaml | trim | nindent 1 }}