# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     run: nginx
#   name: ingress-nginx
#   namespace: ingress-nginx
# spec:
#   ports:
#   - port: 5432
#     protocol: TCP
#     targetPort: 5432
#   selector:
#     run: nginx
