# !!!WARNING!!!
# Edit config in: ./deploy-config/value-secrets.yaml

hydra:
  config:
    dsn: "postgres://mikhailgorbachev666:82M3TLiz7SttMrLu2bTe&@chart-hydra-postgresql-db-postgresql-hydra-service.microservice.svc.cluster.local:5432/db_hydra?sslmode=disable&max_conns=20&max_idle_conns=4"

credentials:
  name: secret-credentials-service-account
  client_id: client-auth-code-service-account
  client_secret: client-secret-service-account