# !!!WARNING!!!
# Edit config in: ./deploy-config/value-secrets.yaml

secrets:
  database_dsn: "postgres://mikhailgorbachev666:82M3TLiz7SttMrLu2bTe&@host-db-postgresql-sa:5432/db_service_account?sslmode=disable&max_conns=20&max_idle_conns=4"
  PGUSER: mikhailgorbachev666
  PGPASSWORD: 82M3TLiz7SttMrLu2bTe&