# !!!WARNING!!!
# Edit config in: ./deploy-config/value-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  database_dsn: {{ required "Deployment database_dsn is required!" .Values.secrets.database_dsn }}
  PGUSER: {{ required "Deployment PGUSER is required!" .Values.secrets.PGUSER }}
  PGPASSWORD: {{ required "Deployment PGPASSWORD is required!" .Values.secrets.PGPASSWORD }}